const express = require("express");
const router = express.Router();
const aurthor = require("./authorization");
router.use("*", aurthor.doAuthAction);
router.use("/users", require("./user"));
router.use("/posts", require("./post"));
router.use("/teams", require("./team"));
router.use("/matches", require("./match"));
router.use("/players", require("./player"));
router.use("/tests", require("./test"));
router.use("/time", require("./time"));
router.use("/recordTeam", require("./recordTeam"));
router.use("/recordPlayer", require("./recordPlayer"));
module.exports = router;
